# Generated by Django 6.0.4 on 2026-04-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conteudo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conteudo',
            new_name='Post',
        ),
    ]
